WORD_BANK = [
    "abandon", "ability", "absence", "academy", "account", "accuse", "achieve", "acquire", "address", "advance",
    "advice", "affect", "afford", "against", "agency", "airline", "airport", "alcohol", "alleged", "already",
    "amazing", "ancient", "anxiety", "anybody", "apology", "appeal", "appoint", "approve", "arguably", "arrange",
    "arrival", "article", "artwork", "assault", "attempt", "attract", "auction", "average", "awesome", "balance",
    "barrier", "battery", "because", "bedroom", "believe", "benefit", "besides", "between", "billion", "biology",
    "blanket", "blessing", "boredom", "bother", "bottle", "boundary", "bravery", "breathe", "briefly", "brother",
    "builder", "burden", "butter", "cabinet", "calculate", "campaign", "capital", "capture", "careful", "carrier",
    "catalog", "category", "caution", "celebrate", "central", "century", "ceremony", "certain", "chamber", "chance",
    "channel", "chapter", "charity", "chicken", "chronic", "circuit", "citizen", "clarify", "classic", "climate",
    "closely", "clothes", "collect", "college", "combine", "comfort", "command", "comment", "company", "compare",
    "compete", "complex", "compose", "concept", "concern", "concert", "conduct", "confirm", "conflict", "connect",
    "consent", "consist", "consult", "contact", "contain", "content", "contest", "context", "control", "convert",
    "convince", "cooking", "correct", "council", "counter", "country", "courage", "crucial", "culture", "curious",
    "current", "curtain", "custom", "damage", "danger", "debate", "decade", "declare", "decline", "default",
    "defense", "deficit", "deliver", "demand", "density", "deposit", "describe", "deserve", "despite", "destroy",
    "develop", "diamond", "digital", "dignity", "disagree", "disaster", "disclose", "discount", "discover", "discuss",
    "disease", "dismiss", "display", "dispute", "distance", "distinct", "district", "diverse", "divorce", "doctrine",
    "document", "domestic", "dominant", "dominate", "donation", "doorway", "double", "drama", "drawing", "dream",
    "driving", "dynamic", "eager", "easily", "economy", "edition", "educate", "effect", "effort", "elderly",
    "election", "element", "embrace", "emerge", "emotion", "emphasis", "empire", "employ", "enable", "encounter",
    "endless", "endorse", "engage", "enhance", "enjoy", "enormous", "enough", "enquiry", "ensure", "entire",
    "entrance", "envelope", "episode", "equally", "equation", "equity", "escape", "essence", "estate", "ethical",
    "evening", "evident", "exactly", "examine", "example", "exceed", "excellent", "exclude", "execute", "exercise",
    "exhibit", "expense", "explain", "explore", "express", "extreme", "faculty", "failure", "famous", "fantasy",
    "fashion", "feature", "federal", "feeling", "fiction", "finance", "finding", "fitness", "flavor", "flexible",
    "flourish", "focused", "follow", "forgive", "fortune", "forward", "freedom", "frequent", "friendly", "frustrate",
    "function", "further", "gallery", "garbage", "general", "genetic", "genuine", "gesture", "glimpse", "glorious",
    "govern", "graduate", "graphic", "gravity", "greatly", "grocery", "guarantee", "guidance", "guilty", "habitat",
    "harmony", "harvest", "heading", "healthy", "hearing", "heavily", "helpful", "heritage", "hesitate", "highway",
    "holiday", "honesty", "horizon", "hormone", "hostile", "housing", "however", "humanity", "humble", "hunger",
    "husband", "hybrid", "iceberg", "illegal", "illness", "imagine", "immense", "impress", "improve", "include",
    "income", "increase", "indicate", "indoor", "infant", "influence", "inform", "inherit", "initial", "inquiry",
    "insight", "inspire", "install", "instant", "instead", "instruct", "insure", "intense", "interest", "internal",
    "interpret", "interval", "intimate", "invasion", "involve", "isolate", "journal", "journey", "justice", "justify",
    "kingdom", "kitchen", "knowing", "laboratory", "landscape", "language", "laughter", "lawyer", "leading", "lecture",
    "legend", "leisure", "liberty", "library", "license", "limited", "literary", "logical", "loyalty", "luxury",
    "machine", "magazine", "maintain", "majority", "manager", "mansion", "marriage", "massive", "material", "maximum",
    "meaning", "measure", "medical", "meeting", "mention", "message", "military", "mineral", "minimum", "miracle",
    "mission", "mistake", "mixture", "monitor", "monthly", "morning", "mortgage", "motion", "mountain", "movement",
    "musical", "mystery", "narrative", "natural", "navigate", "nearby", "network", "neutral", "notable", "nothing",
    "nowhere", "nuclear", "numerous", "nurture", "obesity", "observe", "obstacle", "obvious", "occasion", "offense",
    "officer", "ongoing", "operate", "opinion", "opponent", "opposite", "optimism", "organic", "outcome", "outdoor",
    "outline", "outlook", "outside", "overall", "overcome", "overlook", "package", "painful", "painting", "parade",
    "paradox", "parallel", "parent", "parking", "partial", "partner", "passage", "passion", "patient", "pattern",
    "payment", "penalty", "pension", "percent", "perfect", "perform", "perhaps", "period", "permit", "persist",
    "person", "persuade", "phase", "phenomenon", "philosophy", "physical", "picture", "pioneer", "plastic", "platform",
    "pleasure", "plenty", "pocket", "popular", "portion", "portrait", "position", "positive", "possible", "postpone",
    "poverty", "precious", "predict", "prefer", "prepare", "presence", "preserve", "pressure", "pretend", "prevent",
    "primary", "privacy", "problem", "proceed", "process", "produce", "product", "profile", "program", "progress",
    "project", "promise", "promote", "protect", "protein", "protest", "provide", "publish", "purpose", "pursue",
    "quality", "quarter", "quickly", "quietly", "radical", "railroad", "random", "rapidly", "realize", "rebuild",
    "receive", "recover", "reflect", "reform", "refuse", "regard", "regular", "reject", "relate", "release", "relevant",
    "reliable", "relief", "remain", "remark", "remind", "remote", "remove", "render", "repair", "repeat", "replace",
    "request", "require", "rescue", "research", "reserve", "reside", "resolve", "respect", "respond", "restore",
    "retire", "reveal", "reverse", "review", "reward", "rhythm", "romantic", "routine", "sacred", "safety", "salary",
    "sample", "satisfy", "savings", "science", "scratch", "screen", "script", "search", "season", "second", "secret",
    "section", "segment", "select", "senior", "sensible", "sentence", "separate", "sequence", "serious", "service",
    "session", "settle", "several", "severe", "shadow", "shortly", "shoulder", "shower", "signal", "silence", "similar",
    "simple", "sincere", "singer", "single", "sister", "situation", "slightly", "society", "software", "soldier",
    "solution", "somehow", "someone", "sponsor", "spread", "spring", "stadium", "standard", "station", "statue",
    "status", "steady", "stomach", "storage", "strange", "strategy", "strength", "struggle", "student", "studio",
    "subject", "success", "suggest", "summary", "support", "suppose", "surface", "surgery", "surprise", "survive",
    "suspect", "sustain", "swimming", "symbol", "sympathy", "system", "tackle", "talent", "target", "teacher",
    "teaching", "technique", "technology", "teenager", "television", "temperature", "temporary", "tendency", "tension",
    "theater", "therapy", "therefore", "thorough", "thought", "threat", "through", "ticket", "tightly", "together",
    "tomorrow", "tonight", "totally", "tourist", "towards", "traffic", "training", "transfer", "transform", "translate",
    "transport", "treasure", "treaty", "trigger", "trouble", "trustee", "typical", "ultimate", "universe", "unknown",
    "unusual", "upgrade", "upstairs", "utility", "vacation", "vaccine", "validity", "valuable", "variety", "vehicle",
    "venture", "version", "veteran", "victory", "village", "violent", "virtual", "visible", "visitor", "vitamin",
    "voltage", "volunteer", "voting", "vulnerable", "walking", "warning", "warrant", "wealthy", "weather", "wedding",
    "weekend", "welcome", "welfare", "western", "whisper", "whistle", "widespread", "wildlife", "willing", "window",
    "winner", "witness", "wonder", "workshop", "worship", "writing", "written", "yellow", "yesterday", "yourself",
    "youthful", "zealous", "zodiac", "zombie", "zone", "zoology"
]